/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/coffee_mug.glb --types --transform
Author: The Lister (https://sketchfab.com/MortemNightshade)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-mug-6c95897de04143aeb5c75b7630707d27
Title: Coffee Mug
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import {editable as e} from '@theatre/r3f'

type GLTFResult = GLTF & {
  nodes: {
    Mug_M_Mug_0: THREE.Mesh
  }
  materials: {
    M_Mug: THREE.MeshStandardMaterial
  }
}

export function Coffee(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/coffee_mug-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <e.group theatreKey='coffee_mug' position={[-6.56, -15, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.03}>
        <mesh geometry={nodes.Mug_M_Mug_0.geometry} material={materials.M_Mug} rotation={[-Math.PI, 0, 0]} />
      </e.group>
    </group>
  )
}

useGLTF.preload('/models/coffee_mug-transformed.glb')
