/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/macbook.glb --types --transform --simplify
Author: AR Quick Look USDZ (https://sketchfab.com/pewcus-tunbek-4Buvso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-air-m1-chip-silver-5b40cae179e745ea96cb9d409812a024
Title: Macbook Air M1 Chip Silver
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import {editable as e} from '@theatre/r3f'
import { animated, useSpring } from '@react-spring/three'


type GLTFResult = GLTF & {
  nodes: {
    FxYJZRjJWVjYwLV_1: THREE.Mesh
    FxYJZRjJWVjYwLV_2: THREE.Mesh
    FxYJZRjJWVjYwLV_3: THREE.Mesh
    FxYJZRjJWVjYwLV_4: THREE.Mesh
    FxYJZRjJWVjYwLV_5: THREE.Mesh
    FxYJZRjJWVjYwLV_6: THREE.Mesh
    FxYJZRjJWVjYwLV_7: THREE.Mesh
    FxYJZRjJWVjYwLV_8: THREE.Mesh
    FxYJZRjJWVjYwLV_9: THREE.Mesh
    FxYJZRjJWVjYwLV_10: THREE.Mesh
    FxYJZRjJWVjYwLV_11: THREE.Mesh
    FxYJZRjJWVjYwLV_12: THREE.Mesh
    FxYJZRjJWVjYwLV_13: THREE.Mesh
    FxYJZRjJWVjYwLV_14: THREE.Mesh
    FxYJZRjJWVjYwLV_15: THREE.Mesh
    FxYJZRjJWVjYwLV_16: THREE.Mesh
    FxYJZRjJWVjYwLV_17: THREE.Mesh
    FxYJZRjJWVjYwLV_18: THREE.Mesh
    FxYJZRjJWVjYwLV_19: THREE.Mesh
    FxYJZRjJWVjYwLV_20: THREE.Mesh
    FxYJZRjJWVjYwLV_21: THREE.Mesh
    FxYJZRjJWVjYwLV_22: THREE.Mesh
    FxYJZRjJWVjYwLV_23: THREE.Mesh
    FxYJZRjJWVjYwLV_24: THREE.Mesh
  }
  materials: {
    zSTXkYgEDkTgmAG: THREE.MeshStandardMaterial
    ToljNQRLmTtuwNl: THREE.MeshStandardMaterial
    NYJQUGhFFttpmSc: THREE.MeshStandardMaterial
    aqhAfpkxnZPmIhk: THREE.MeshStandardMaterial
    TQlUdQskMqFOeNF: THREE.MeshStandardMaterial
    ulJMfFlutqmNQMW: THREE.MeshStandardMaterial
    XmFnkDCORGzfeME: THREE.MeshStandardMaterial
    RyMGdvvvrICYPYi: THREE.MeshStandardMaterial
    QvIzXEFfzNggOmB: THREE.MeshStandardMaterial
    peGpnBqcYHYUYsw: THREE.MeshStandardMaterial
    fNwAJBobjIFRfvB: THREE.MeshStandardMaterial
    ZRtDNbbFJTtCHrm: THREE.MeshStandardMaterial
    sQFBWaBkjsgwGvu: THREE.MeshStandardMaterial
    FXtoXdXSZfIeavz: THREE.MeshStandardMaterial
    oERDOwdFTcMQzDv: THREE.MeshStandardMaterial
    OthLhWgjvJJXXXx: THREE.MeshStandardMaterial
    initialShadingGroup: THREE.MeshStandardMaterial
    stkDfiDJRcgomRA: THREE.MeshStandardMaterial
    TUaXhUUzDBaiMXN: THREE.MeshStandardMaterial
    HOLRHAuxFvQaQOG: THREE.MeshStandardMaterial
    vfSIsEZWCUAlBZY: THREE.MeshStandardMaterial
    ICUyIsjyBwzbuKl: THREE.MeshStandardMaterial
    FxVDqFpCAhktJsF: THREE.MeshStandardMaterial
    uzwDFWlQEbgKaKk: THREE.MeshStandardMaterial
  }
}

export function MacBook(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/macbook-transformed.glb') as GLTFResult

  const {opacity: materialOpacity} = useSpring({
    from: {
      opacity: 0
    },
    to: {
      opacity: 1
    }
  });

  

  return (
    <group {...props} dispose={null} >
      <e.group  theatreKey='macbook' scale={1} position={[0,-40,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_1.geometry} material={materials.zSTXkYgEDkTgmAG} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_2.geometry} material={materials.ToljNQRLmTtuwNl} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_3.geometry} material={materials.NYJQUGhFFttpmSc} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_4.geometry} material={materials.aqhAfpkxnZPmIhk} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_5.geometry} material={materials.TQlUdQskMqFOeNF} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_6.geometry} material={materials.ulJMfFlutqmNQMW} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_7.geometry} material={materials.XmFnkDCORGzfeME} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_8.geometry} material={materials.RyMGdvvvrICYPYi} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_9.geometry} material={materials.QvIzXEFfzNggOmB} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_10.geometry} material={materials.peGpnBqcYHYUYsw} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_11.geometry} material={materials.fNwAJBobjIFRfvB} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_12.geometry} material={materials.ZRtDNbbFJTtCHrm} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_13.geometry} material={materials.sQFBWaBkjsgwGvu} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_14.geometry} material={materials.FXtoXdXSZfIeavz} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_15.geometry} material={materials.oERDOwdFTcMQzDv} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_16.geometry} material={materials.OthLhWgjvJJXXXx} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_17.geometry} material={materials.initialShadingGroup} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_18.geometry} material={materials.stkDfiDJRcgomRA} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_19.geometry} material={materials.TUaXhUUzDBaiMXN} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_20.geometry} material={materials.HOLRHAuxFvQaQOG} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_21.geometry} material={materials.vfSIsEZWCUAlBZY} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_22.geometry} material={materials.ICUyIsjyBwzbuKl} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_23.geometry} material={materials.FxVDqFpCAhktJsF} />
          <mesh geometry={nodes.FxYJZRjJWVjYwLV_24.geometry} material={materials.uzwDFWlQEbgKaKk} />
        </group>
      </group>
      </e.group>
    </group>
  )
}

useGLTF.preload('/models/macbook-transformed.glb')
